export const articles = [
  {
    id: 1,
    img: "/triviaApp.png",
    title: "Unleash Your Inner Volcanologist with This Engaging Trivia App",
    p: "Are you fascinated by volcanoes? Do you think you have what it takes to be a volcanologist? Well, now’s your chance to find out! Introducing the Volcano Trivia App — an interactive and educational platform designed to test your knowledge of all things volcanic.",
    url: "https://medium.com/@claytoncripe/unleash-your-inner-volcanologist-with-this-engaging-trivia-app-57391580c570",
    date: "Mar 27th 2024",
  },
  {
    id: 2,
    img: "/contextCode.png",
    title: "React Context API",
    p: "When we talk about React Context a lot of us may think of the origins of where it came from which was Remix. Still, certain parts of Remix got incorporated into React at a certain point.",
    url: "https://medium.com/@claytoncripe/react-context-api-816fd0533338",
    date: "Mar 7th 2023",
  },
  {
    id: 3,
    img: "",
    title: "Understanding Big O Notation: A Professional Overview",
    p: "Big O notation is a mathematical concept used to describe the performance or complexity of an algorithm.",
    url: "https://medium.com/@claytoncripe/understanding-big-o-notation-a-professional-overview-3de6dcdffa01",
    date: "June 27th 2024",
  },
  {
    id: 4,
    img: "/binarySearch.png",
    title: "Understanding Binary Search: A Practical Guide",
    p: "When dealing with search algorithms, the order of the data set plays a crucial role in determining which algorithm to use.",
    url: "https://medium.com/@claytoncripe/understanding-binary-search-a-practical-guide-8c08dbdda831",
    date: "June 28th 2024",
  },
  {
    id: 5,
    img: "/crystalBalls.png",
    title: "Optimizing the Two Crystal Balls Problem",
    p: "Imagine you are in a hundred-story building with two crystal balls. You need to determine the exact floor at which the crystal balls will break when dropped, and you want to find the most efficient way to do this.",
    url: "https://medium.com/@claytoncripe/optimizing-the-two-crystal-balls-problem-5ef21d3dfdfa",
    date: "June 28th 2024",
  },
  {
    id: 6,
    img: "/bubbleSort1.png",
    title: "Bubble Sort: The Simplest Sorting Algorithm",
    p: "Bubble sort is one of the simplest sorting algorithms, known for its ease of implementation and visualization.",
    url: "https://medium.com/@claytoncripe/bubble-sort-the-simplest-sorting-algorithm-2d1493d8f9b0",
    date: "June 30th 2024",
  },
  {
    id: 7,
    img: "",
    title: "Understanding Linked Lists: A Beginner’s Guide",
    p: "Linked lists are a fundamental data structure that many beginners encounter when diving into computer science. They organize data in such a way that allows efficient insertion and deletion operations.",
    url: "https://medium.com/@claytoncripe/understanding-linked-lists-a-beginners-guide-7b60b156a5c4",
    date: "July 2nd 2024",
  },
  {
    id: 8,
    img: "/queue.png",
    title: "Understanding Queues: A Beginner’s Guide",
    p: "Queues are one of the most common data structures, widely used in various applications. They are a specific implementation of a linked list",
    url: "https://medium.com/@claytoncripe/understanding-queues-a-beginners-guide-02650250e2b3",
    date: "July 2nd 2024",
  },
  {
    id: 9,
    img: "/stack.png",
    title: "Understanding Stacks",
    p: "Stacks are a fundamental data structure that operate on the Last In, First Out (LIFO) principle. They are widely used in various applications",
    url: "https://medium.com/@claytoncripe/understanding-stacks-592c36f91ea7",
    date: "July 4th 2024",
  },
]