export const portfolioItems = [
  {
    img: "/RoyalCaninePic.png",
    caption: "The Royal Canine",
    desc: "this is a freelance project for a self service dog wash company",
    category: "React App",
    url: "https://www.theroyalcaninedogwash.com",
    key: 0,
    id: 5,
  },
  {
    img: "/drAlderSite.png",
    caption: "Alder Family Chiropractic",
    desc: "I helped a chiropractor with his website and made it more modern and updated",
    category: "WordPress",
    url: "https://alderfamilychiropractic.com/",
    key: 1,
    id: 4,
  },
  {
      img: "/triviaApp.png",
    caption: "Volcano Trivia App",
    desc: "This is a trivia app that I made for my capstone project at Devslopes which showcases my skills in Vue, Typescript, tailwindcss, and more. since I have a always enjoyed learning about volcanoes and other natural wonders I decided to make a trivia app about them.",
    category: "Vue App",
    url: "https://volcano-trivia-app.vercel.app/",
    key: 2,
    id: 3,
  },
  // {
  //   img: porfolio,
  //   caption: "Portfolio landing page",
  //   desc: "This is a portfolio site that has some nice features built into it like light and dark modes and popups and more",
  //   category: "Landing Page",
  //   url: "https://claysfolio.netlify.app/",
  //   key: 2,
  //   id: 3,
  // },
  // {
  //   img: sass,
  //   caption: "Front Landing page",
  //   desc: "This is a software as a service or SaaS for short landing page",
  //   category: "Landing Page",
  //   url: "https://clayssass.netlify.app/",
  //   key: 3,
  //   id: 2,
  // },
  {
    img: "/clothingEssentialsPic.png",
    caption: "Clothing Essentials E-commerce site",
    desc: "This is a E-commerce Site that is similar amazon but without the full back-end hooked up as I didn't want to get into the business of selling clothing",
    category: "React App",
    url: "https://iconians.github.io/shopperApp/",
    key: 4,
    id: 1,
  },
  // {
  //   img: podpic,
  //   caption: "Podcast page",
  //   desc: "this is an example of a podcast webpage ",
  //   category: "Landing Page",
  //   url: "https://clayspodcastproject.netlify.app/",
  //   key: 5,
  //   id: 0,
  // },
];
