export const portfolioItems = [
  {
    img: "/RoyalCaninePic.png",
    caption: "The Royal Canine",
    desc: "A modern, responsive website built for The Royal Canine, a self-service dog wash company. Developed with React to deliver a clean, user-friendly experience that highlights the company’s services and makes it easy for customers to learn more and visit in person.",
    category: [
      "React",
      "Frontend Development",
      "Responsive Design",
      "Small Business Website",
    ],
    url: "https://www.theroyalcaninedogwash.com",
    github: "#",
    key: 0,
    id: 5,
  },
  {
    img: "/triviaApp.png",
    caption: "Volcano Trivia App",
    desc: "An interactive trivia app built as my capstone project at Devslopes Academy. Developed with Vue, TypeScript, TailwindCSS, and Supabase, it showcases my ability to create responsive, data-driven applications. Inspired by my fascination with volcanoes and natural wonders, the app offers an engaging way for users to test their knowledge while exploring the world’s most powerful phenomena.",
    category: ["Vue", "TypeScript", "TailwindCSS", "Supabase"],
    url: "https://volcano-trivia-app.vercel.app/",
    github: "#",
    key: 2,
    id: 3,
  },
  {
    img: "/constructionSite.png",
    caption: "Downriver Renovations",
    desc: "A professional website built for Downriver Renovations, a construction and remodeling company. Developed with Next.js, this freelance project focuses on performance, responsive design, and clear presentation of services to help the business reach more local clients and showcase completed work.",
    category: ["Next.js", "React", "Frontend Development", "Responsive Design"],
    url: "https://www.downriverrenovations.com/",
    github: "#",
    key: 6,
    id: 6,
  },
];
